[preferences]

prefix = "."
bot_name = "Bolt"

[logging]

levels_to_ignore = ["INFO", "DEBUG"]

[cogs]

disabled = []

[markdown]

support_server = "https://discord.gg/yourserver"
github_repo = "https://github.com/your/repo"
invite_link = "https://example.com/invite"