[preferences]

prefix = "."
bot_name = "Bolt"

[logging]

levels_to_ignore = ["INFO", "DEBUG"]

[cogs]

disabled = []

[markdown]

support_server = "https://discord.gg/hF6mgCE3gT"
github_repo = "https://github.com/sparkhere-sys/bolt"
invite_link = "https://sparkhere-sys.github.io/bolt"