exclude = [
  ".git",
  ".venv",
  "__pycache__",
  "data",
  ".vscode",
  ".ruff-cache",
  "site-packages",
]

line-length = 128
indent-width = 2
target-version = "py313"

[format]

quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = true
line-ending = "lf" # .gitattributes makes sure of this too
